### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by nurglexp** [ich777/docker-magicmirror2#2]
Hi, is this still maintained?
I've tried installing and it doesn't seem to run. From the logs:

---Ensuring UID: 99 matches user---
---Ensuring GID: 100 matches user---
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Taking ownership of data...---
---Starting...---
---Can't get latest version number, putting server into sleep mode---

**Comment by ich777** [comment]
Yes, it is still maintained, I assume you are using the container on Unraid?
Do you have any AdBlocking somewhere on your network? Make sure you don't block `api.github.com`

I have now multiple reports that if you are using `pialert` it will eat up all your GitHub API calls because of a bug, see also as reported [here](https://github.com/ich777/unraid-coral-driver/issues/7#issuecomment-1642754105).

**Comment by ich777** [comment]
Tried it on my server and it is working just fine, attached the log and a screenshot: [mm2.log](https://github.com/ich777/docker-magicmirror2/files/12113083/mm2.log)

![grafik](https://github.com/ich777/docker-magicmirror2/assets/28066518/93d0b084-8f67-47c7-a257-34348b73f6e1)

(This is a completely fresh installation from the container)

**Comment by nurglexp** [comment]
Thank you, that's exactly my issue!

{"message":"API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

i'll disable PiAlert for now. Appreciate the help!
